### ISSUE TITLE
Change request: Optional cover art display, since default cover art widget is really small

### ISSUE THREAD

**Issue by hzulla** [janbar/noson-app#194]
While listening to Spotify playlists, sometimes a track's cover artwork catches my attention. I wish I could look at it, but noson only shows a small cover art widget on my computer. It would be really nice to have an optional big cover art widget just so that the user can look at it.

Thanks for the great app!

**Comment by janbar** [comment]
When you reduce the width of the app window, you should have the big cover.
 
<img width="865" alt="Capture d’écran 2022-10-06 à 14 54 52" src="https://user-images.githubusercontent.com/2353635/194318664-9d88a0d3-c257-4186-ad43-90d4bffe6957.png">
<img width="356" alt="Capture d’écran 2022-10-06 à 14 56 01" src="https://user-images.githubusercontent.com/2353635/194318703-bdd58199-74ef-47d9-ba15-f9728ff8d9db.png">

In large window mode, I cannot grow the cover art because it needs space for the queue list.

**Comment by hzulla** [comment]
Ok, thanks for pointing it out!

Here's why I possibly didn't find this feature:

- use the small-width view of noson with the large cover art display
- make the window wider
- large window mode is shown
- now reduce the width again
- noson doesn't show the large cover art display, but the content of whatever was in the left side of the large window
- large cover art display only returns if I click the "now playing" widget below in small-width window mode

So the feature wasn't obvious to find.
