### ISSUE TITLE
openSUSE packaging

### ISSUE THREAD

**Issue by bosim** [janbar/noson-app#45]
Hi

Really a nice sonos application you have created! Really appreciate it.

I have started packaging the application for openSUSE. I have a working example. I think a few small improvements from a packaging perspective could be archived:

* if libnoson is present it should be autodetected by cmake similar to the ssl/zlib libraries
* I need a patch for the install prefix, since it is per default /usr when using the suse macros, wonder if it could be resolved for all distros.

If you are interested my spec file/patch is here:

https://build.opensuse.org/package/show/home:bosim:noson/noson-app

Thanks
Bo

**Comment by janbar** [comment]
Hi Bo,

libnoson hasn't been versionned and for this reason the build need to be
statically linked with the provided snapshot.
The application core binaries should be installed under the standard
prefix: $PREFIX/$LIBDIR/, in folder "noson". Those contains also the qml
module NosonApp (NosonApp/libNosonAppbackend.so, NosonApp/qmldir). So you
shouldn't need a patch to change that.

Below a sample build in my Opensuse Leap 42.3. For it I need to install
manually the framework Qt-5.9 because provided version is only 5.6.
Considering PREFIX=/usr

cmake .. -DCMAKE_BUILD_TYPE=Release
-DCMAKE_PREFIX_PATH=/usr/local/Qt/5.9.5/gcc_64/
-DCMAKE_INSTALL_PREFIX=/usr

-- Install configuration: "Release"
-- Installing: /usr/bin/noson-app
-- Installing: /usr/share/applications/io.github.janbar.noson.desktop
-- Installing: /usr/share/icons/hicolor/256x256/apps/noson.png
-- Installing: /usr/share/metainfo/io.github.janbar.noson.appdata.xml
-- Installing: /usr/lib64/noson/noson-gui
-- Installing: /usr/lib64/noson/NosonApp/libNosonAppbackend.so
-- Set runtime path of
"/usr/lib64/noson/NosonApp/libNosonAppbackend.so" to ""
-- Installing: /usr/lib64/noson/NosonApp/qmldir
-- Installing: /usr/lib64/noson/noson-cli

regards.

2018-06-30 14:17 GMT+02:00 Bo Simonsen <notifications@github.com>:

**Comment by janbar** [comment]
Hi,

I updated noson library to be published as is (tag 1.8.0). And I reviewed
the cmake project noson-app to be able to link with the provided shared lib
noson by the target system. Hope it can help.

regards

2018-06-30 16:24 GMT+02:00 Bo Simonsen <notifications@github.com>:

**Comment by bosim** [comment]
Hi Jean-Luc

Thanks for looking into this. I will look at your changes during a weekend. Maybe when the backend API becomes stable, it would be feasible to have it dynamic linked.

Noson-app is now installable on openSUSE https://software.opensuse.org/package/noson-app?search_term=noson-app

Maybe you want to update the homepage. 

Thanks!

Bo

**Comment by janbar** [comment]
Great !

Also with the commit 580ce039 I use a portable way to insure LIBDIR is the absolute path either on the debian or bsd target. So with the last tag 3.6.2 you won't need to use a patch to fix the mess.

**Comment by bosim** [comment]
Will check it out. Thanks :)

**Comment by bosim** [comment]
Works great building libnoson seperately! Thanks, really appreciate it!

**Comment by bosim** [comment]
@janbar Hi, libnoson is soon reaching openSUSE:Factory and thereby Tumbleweed quite soon. Could you maybe add a cmake option to force dynamic linking of noson-app with libnoson. If it is possible I will submit noson-app, and people can install the app directly without additional sources.

**Comment by janbar** [comment]
Hi, it should be possible. I will let you know soon.

Le sam. 28 juil. 2018 09:06, Bo Simonsen <notifications@github.com> a
écrit :

**Comment by bosim** [comment]
Hmm, doesn't seem to work, still libnoson is not in ldd output. Please see the spec file here
https://build.opensuse.org/package/view_file/multimedia:apps/noson-app/noson-app.spec?expand=1

**Comment by janbar** [comment]
I uploaded the rpm from pkgs.org to extract the file `libNosonAppbackend.so` and the ldd output shows me `libnoson.so.1` as we expected. Idem for `noson-cli` the ldd output shows me libnoson. I guess you tried to examine the wrong binary file i.e `noson-gui` which is linked with its embedded module libNosonAppbackend only.

**Comment by janbar** [comment]
Running the app from the binaries of the rpm work great. Hope Suse users will enjoy with it.

**Comment by bosim** [comment]
Ah, didn't know that, ldd does not show it (noson-gui). Is it static linked to the backend library?

**Comment by bosim** [comment]
noson-app submitted for openSUSE Factory:
https://build.opensuse.org/request/show/627439

**Comment by janbar** [comment]
From the RPM package the binary libNosonAppbackend.so is dynamically linked with libnoson, libcrypto, libssl. The binary noson-cli (a cli tool for handyman) is dynamically linked with libnoson. Finally noson-gui is the launcher for the frontend: it is a QmlEngine and it loads required plugins at runtime as libNosonAppbackend.so and few others from the Qt distribution of the os.

**Comment by janbar** [comment]
All seems good. Thanks

**Comment by bosim** [comment]
@janbar just for information I expect noson + noson-app to be included in openSUSE LEAP 15.1 (It is already in tumbleweed).

**Comment by janbar** [comment]
@bosim the new release 3.11.2 is now out and adds some great new features for linux users: streaming of local audio files and the pulseAudio output.

**Comment by bosim** [comment]
@janbar Great news! Really a neat feature, however I have problems compiling eventhough libnoson is compiled with libpulse + libflac support. See build log
https://build.opensuse.org/build/multimedia:apps/openSUSE_Leap_15.1/x86_64/noson-app/_log

**Comment by janbar** [comment]
libnoson 1.12.x requires new dependencies:

- lib FLAC
- lib FLAC++
- lib Pulse
- lib Pulse-simple

You have to rebuild libnoson with those depends and noson-app too.

**Comment by bosim** [comment]
> You have to rebuild **libnoson** with those depends and then **noson-app** too, probably adding in the specs files the lines below:
> 
> BuildRequires: libFLAC8
> BuildRequires: libFLAC++6
> BuildRequires: libpulse-devel

Did the trick! Just wonder why noson-app needs link to pulse and flac when libnoson is linked already.

Just tested the pulseaudio functionality, really cool!

**Comment by bosim** [comment]
By the way noson and noson-app are included in 15.1, assume it is going to be the first distro shipping with noson included.
